version: 2
project_name: cnpg

release:
  github:
    owner: criteo-forks
    name: cloudnative-pg

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
- id: manager
  binary: manager/manager_{{ .Arch }}
  main: cmd/manager/main.go
  no_unique_dist_dir: true
  gcflags:
    - all=-trimpath={{.Env.GOPATH}};{{.Env.PWD}}
  ldflags:
    - -s
    - -w
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildVersion={{.Env.VERSION}}
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildCommit={{.Env.COMMIT}}
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildDate={{.Env.DATE}}
  goos:
    - linux
  goarch:
    - amd64
    - arm64

- id: manager-race
  binary: manager/manager_{{ .Arch }}
  main: cmd/manager/main.go
  no_unique_dist_dir: true
  skip: >-
    {{ if and (isEnvSet "RACE") (eq .Env.RACE "true") }}false{{ else }}true{{ end }}
  gcflags:
    - all=-trimpath={{.Env.GOPATH}};{{.Env.PWD}}
  ldflags:
    - -race
    - -s
    - -w
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildVersion={{.Env.VERSION}}
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildCommit={{.Env.COMMIT}}
    - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildDate={{.Env.DATE}}
  goos:
    - linux
  goarch:
    - amd64
    - arm64

- id: kubectl-cnpg
  binary: kubectl-cnpg
  main: cmd/kubectl-cnpg/main.go
  gcflags:
  - all=-trimpath={{.Env.GOPATH}};{{.Env.PWD}}
  ldflags:
  - -s
  - -w
  - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildVersion={{.Env.VERSION}}
  - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildCommit={{.Env.COMMIT}}
  - -X github.com/criteo-forks/cloudnative-pg/pkg/versions.buildDate={{.Env.DATE}}
  goos:
  - linux
  goarch:
  - amd64
  - 386
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: ppc64le
  - goos: windows
    goarch: s390x

archives:
- name_template: >-
    kubectl-cnpg_{{ .Version }}_
    {{- .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ end }}
  builds:
  - kubectl-cnpg

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  disable: true

krews:
  - name: cnpg
    homepage: https://github.com/criteo-forks/cloudnative-pg
    short_description: 'Manage your CloudNativePG clusters'
    skip_upload: true
    description: 'This plugin provides multiple commands to help you manage your CloudNativePG clusters.'